# Generated by Django 5.0.6 on 2024-05-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
