# Generated by Django 5.0.6 on 2024-06-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistAPI', '0005_todoitem_user_alter_todoitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
