# Generated by Django 5.0.6 on 2024-06-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistAPI', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
